In [ ]:
import numpy as np
import matplotlib.pyplot as plt  #para graficar
import scipy
import cvxopt

**COMENTARIOS**

In [ ]:
#Esto es un comentario de una línea
"""Esto es un comentario de 
varias líneas"""

'Esto es un comentario de \nvarias líneas'

In [ ]:
""" Este es un comentario multilinea. La
siguiente parte realiza una serie
de cosas muy interesantes """

' Este es un comentario multilinea. La\nsiguiente parte realiza una serie\nde cosas muy interesantes '

**VARIABLES**

In [ ]:
#Constantes: imprimimos y comprobamos los resultados

In [ ]:
print("Esto es una constante numérica:" + str(12345))

Esto es una constante numérica:12345


In [ ]:
print("Esto es una cadena de texto:" + "Hola que tal")

Esto es una cadena de texto:Hola que tal


In [ ]:
#Variable numérica
variable_numerica = 3

In [ ]:
#Variable cadena de texto (string)
variable_string ="Hola"
print("Esto es una constante numérica:" + str(variable_numerica))
print("Esto es una cadena de texto:" + variable_string)

Esto es una constante numérica:3
Esto es una cadena de texto:Hola


In [ ]:
#Los nombres son sensibles a las mayúsculas
Variable =5
variable =2
print(Variable)
print(variable)

5
2


In [ ]:
#Si queremos declarar un valor constante para todo el programa, y no queremos introducir el valor exacto de forma reiterada 
#podemos hacer así:
CONSTANTE_PRUEBA=5

In [ ]:
#Python tiene los siguientes tipos de datos integrados de forma predeterminada, en estas categorías:
#Tipo de texto:	str
#Tipos numéricos:	int, float, complex
#Tipos de secuencia:	list, tuple, range
#Tipo de mapeo:	dict
#Establecer tipos:	set,frozenset
#Tipo booleano:	bool
#Tipos binarios:	bytes, bytearray, memoryview
#Ninguno Tipo:	NoneType

In [ ]:
x = "Hello World" #Tipo de texto:	str
#display x:
print(x)

#display the data type of x:
print(type(x)) 

x = 20 #Tipos numéricos:	int
x = 20.5 #Tipos numéricos: float
x = 1j #Tipos numéricos: complex
x = ["apple", "banana", "cherry"] #Tipos de secuencia:	list
x = ("apple", "banana", "cherry") #Tipos de secuencia: tuple
x = range(6) #Tipos de secuencia: range
x = {"name" : "John", "age" : 36} #Tipo de mapeo:	dict
x = {"apple", "banana", "cherry"} #Establecer tipos:	set
x = frozenset({"apple", "banana", "cherry"}) #Establecer tipos:frozenset 
#Los frozenset en Python son una estructura de datos muy similar a los set, con la salvedad de que son inmutables, 
#es decir, no pueden ser modificados una vez declarados.
x = True #Tipo booleano:	bool
x = b"Hello" #Tipos binarios:	bytes, 
x = bytearray(5) # Tipo binarios: bytearray
#bytearray():Es el método que devuelve un objeto bytearray (es decir, una matriz de bytes) que es mutable (se puede modificar)
x = memoryview(bytes(5)) #Tipo memoryview
x = None #Tipo:	NoneType

Hello World
<class 'str'>


In [ ]:
#Podemos saber el tipo de variable concreta con la fucnión Type
#str (cadena de texto)
#int (entero)
#float (número real)
#¿De qué tipo es la variable?
print(type(variable))
#¿De qué tipo es la variable_string?
print(type(variable_string))

<class 'int'>
<class 'str'>


In [ ]:
#Conversión de tipos
numero_real =3.96
print(numero_real)
print(str(numero_real))
print(type(numero_real))
print(type(str(numero_real)))
print(int(numero_real))
print(int("5"))

3.96
3.96
<class 'float'>
<class 'str'>
3
5


In [ ]:
#Tipo de datos complejos
#Acceso a elementos de una cadena mediante la posición
cadena= "Esto es una cadena"
print(cadena[5]) # ten en cuenta que el índice comienza en cero
print(cadena[5:9]) #Rango de valores de 5 a 9
print(cadena [:5]) #Hasta 5
print(cadena[5:]) #de 5 en adelante
print(len(cadena)) #longitud

e
es u
Esto 
es una cadena
18


In [ ]:
#Los conjuntos son colecciones no ordenadas y sin elementos repetidos.
#Conjuntos en Python
gastronomia = {'ajiaco','paella','cocido','empanada','hamburguesa'}
print(gastronomia)
print(type(gastronomia))
print(gastronomia.pop())#elimina al azar un elemento del conjunto
print(gastronomia) # cocido ha desaperecido


{'cocido', 'hamburguesa', 'paella', 'ajiaco', 'empanada'}
<class 'set'>
cocido
{'hamburguesa', 'paella', 'ajiaco', 'empanada'}


In [ ]:
#Elementos del conjunto
print(next(iter(gastronomia)))

ajiaco


In [ ]:
marks = [65, 71, 68, 74, 61]
print(marks)
# convertir lista a iterador
iterator_marks = iter(marks)

#La función next() devuelve el siguiente elemento del iterador.
# el siguiente elemento es el primer elemento
marks_1 = next(iterator_marks)
print(marks_1)

# encontrar el siguiente elemento que es el segundo elemento
marks_2 = next(iterator_marks)
print(marks_2)

# encontrar el siguiente elemento que es el segundo elemento
marks_3 = next(iterator_marks)
print(marks_3)

[65, 71, 68, 74, 61]
65
71
68


In [ ]:
#Las listas son una de las estructuras más frecuente en Python, permite acumular y
#manipular datos de forma sencilla.
#Trabajando con listas
gastronomia=['ajiaco','paella','cocido','empanada','hamburguesa']
#tipo?
print(type(gastronomia))
print(len(gastronomia))

<class 'list'>
5


In [ ]:
#Asignar una variable a la lista
platos_tipicos=set(gastronomia)
print(platos_tipicos)
print(type(platos_tipicos))

{'hamburguesa', 'ajiaco', 'cocido', 'empanada', 'paella'}
<class 'set'>


In [ ]:
#Condicionales
En_Bogota= 'ajiaco' in platos_tipicos
print(En_Bogota)

True


In [ ]:
gastronomia.insert(len(gastronomia), 'frijoles') #insertar al final
print(gastronomia)

['ajiaco', 'paella', 'cocido', 'empanada', 'hamburguesa', 'frijoles']


In [ ]:
# crear una lista de vocales
vowel = ['a', 'e', 'i', 'u']

# 'o' se inserta en la cuarta posición
vowel.insert(3, 'o')

print('List:', vowel)

# Output: List: ['a', 'e', 'i', 'o', 'u']

List: ['a', 'e', 'i', 'o', 'u']


In [ ]:
# El index()método devuelve el índice del elemento especificado en la lista.
animals = ['cat', 'dog', 'rabbit', 'horse']

# obtener el índice de 'dog'
index = animals.index('dog')

print(index)

# Output: 1

1


In [ ]:
#Por último, mencionaremos las tuplas, una tupla es una lista inmutable.
#Las tuplas se utilizan para almacenar varios elementos en una sola variable.
tupla=[1,2,3,4,5]
print(tupla)
tupla[0]=99
print(tupla) #por eso esto no es una tupla


[1, 2, 3, 4, 5]
[99, 2, 3, 4, 5]


In [ ]:
tupla2={1,2,3,4,5}
print(tupla2)
#tupla2[0]=99 #Algo salió mal
#Por esto tupla2 sí es una tupla

{1, 2, 3, 4, 5}


In [ ]:
#Otra estructura de datos interesante es el diccionario. Un diccionario permite
#identificar a sus elementos a través de una clave. La siguiente imagen muestra un
#ejemplo típico de uso.

In [ ]:
#Diccionarios
diccionario={'nombre': 'Juan', 'edad':22, 'cursos': ['Python', 'Machine Learning', 'R']}
#Accediendo a los valores
print(diccionario['nombre'])
print(diccionario['edad'])
print(diccionario['cursos'])

Juan
22
['Python', 'Machine Learning', 'R']


In [ ]:
#Recorrido modo lista
print(diccionario['cursos'][0])
#Recorrer todo el diccionario
for key in diccionario:
  print(key,":",diccionario[key])

Python
nombre : Juan
edad : 22
cursos : ['Python', 'Machine Learning', 'R']


In [ ]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])
print(escalar)
print(vector)
print(matriz)
print(tensor)

5.679
[3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


***VECTORES***

In [ ]:
# Vector como lista de Python
v1 = [2, 4, 6]
v1

[2, 4, 6]

In [ ]:
# Vectores con numpy
import numpy as np

v2 = np.ones(3) # vector de solo unos.
v2

array([1., 1., 1.])

In [ ]:
v3 = np.array([1, 3, 5]) # pasando una lista a las arrays de numpy
v3

array([1, 3, 5])

In [ ]:
v4 = np.arange(1, 8) # utilizando la funcion arange de numpy
v4

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.sort(v4) #ordenar de manera ascendente

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
-np.sort(-v4) #ordenar de manera descendente

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
#Matriz unidimensional vertical
for i in range(1,7):
  print(i)
  print('\n')

1


2


3


4


5


6




In [ ]:
#matriz unidimensional horinzontal
for i in range(1,7):
  print(i, end=' ')

1 2 3 4 5 6 

**OPERACIONES CON VECTORES**

In [ ]:
# Ejemplo en Python
x = np.arange(1, 5) #genera un conjunto de números entre un valor de inicio y uno final
y = np.array([2, 4, 6, 8])
x, y

(array([1, 2, 3, 4]), array([2, 4, 6, 8]))

In [ ]:
#otros ejemplos de np.arange
z= np.arange(2,10,3)
z

array([2, 5, 8])

In [ ]:
#otros ejemplos de np.arange
z0= np.arange(0,10,2)
z0

array([0, 2, 4, 6, 8])

In [ ]:
# otro ejemplo de uso np.arange
z1= np.arange(5)
z1

array([0, 1, 2, 3, 4])

In [ ]:
#realizando filtro
z1<3

array([ True,  True,  True, False, False])

In [ ]:
z1[z1<3] #filtro, menores que tres

array([0, 1, 2])

In [ ]:
# sumando dos vectores numpy
x + y

array([ 3,  6,  9, 12])

In [ ]:
# restando dos vectores
x - y

array([-1, -2, -3, -4])

In [ ]:
# multiplicando por un escalar
x * 2

array([2, 4, 6, 8])

In [ ]:
y * 3

array([ 6, 12, 18, 24])

In [ ]:
array_ceros= np.zeros(5)
array_ceros

array([0., 0., 0., 0., 0.])

**Producto escalar **

In [ ]:
#El producto escalar de dos vectores se define como la suma de los productos de sus elementos

In [ ]:
# Calculando el producto escalar de los vectores x e y
x @ y

60

In [ ]:
# hay dos formas de escribir el producto:
sum(x * y), np.dot(x, y)

(60, 60)

**Matrices**

In [ ]:
#Python no tiene un tipo de dato incorporado para trabajar con matrices, sin embargo podemos tratar la matriz como una lista de listas,

In [ ]:
#Ejemplo de matrices
C=[[1,2,0,4],
   [5,6,3,7],
   [3,8,9,10]]
print("C=",C)
print("C[1]=",C[1]) #segunda fila
print("C[1][2]=",C[1][2]) # tercer elemento de la segunda fila
print("C[0][-1]=",C[0][-1]) #último elemento de la primera fila


C= [[1, 2, 0, 4], [5, 6, 3, 7], [3, 8, 9, 10]]
C[1]= [5, 6, 3, 7]
C[1][2]= 3
C[0][-1]= 4


In [ ]:
#matriz bidimensional con un for anidado
for i in range(1,7):
    for j in range(1,7):
        print(1, end=' ')
    print(' ')

1 1 1 1 1 1  
1 1 1 1 1 1  
1 1 1 1 1 1  
1 1 1 1 1 1  
1 1 1 1 1 1  
1 1 1 1 1 1  


In [ ]:
#matriz bidimensional con un for anidado
for i in range(1,7):
    for j in range(1,7):
        print(f'({i},{j})', end=' ')
    print(' ')

(1,1) (1,2) (1,3) (1,4) (1,5) (1,6)  
(2,1) (2,2) (2,3) (2,4) (2,5) (2,6)  
(3,1) (3,2) (3,3) (3,4) (3,5) (3,6)  
(4,1) (4,2) (4,3) (4,4) (4,5) (4,6)  
(5,1) (5,2) (5,3) (5,4) (5,5) (5,6)  
(6,1) (6,2) (6,3) (6,4) (6,5) (6,6)  


In [ ]:
# Ejemplo en Python
A = np.array([[1, 3, 2],
              [1, 0, 0],
              [1, 2, 2]])

B = np.array([[1, 0, 5],
              [7, 5, 0],
              [2, 1, 1]])
# suma de las matrices A y B
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [ ]:
A[0,0] #seleccionar el primer término

1

In [ ]:
A[1,2] #seleccionar otro elemento

0

In [ ]:
A[1,:] #seleccionar por fila

array([1, 0, 0])

In [ ]:
A[:,1]#seleccionar por columna

array([3, 0, 2])

In [ ]:
# resta de matrices
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [ ]:
# multiplicando matrices por escalares
A * 2

array([[2, 6, 4],
       [2, 0, 0],
       [2, 4, 4]])

In [ ]:
B * 3

array([[ 3,  0, 15],
       [21, 15,  0],
       [ 6,  3,  3]])

In [ ]:
# ver la dimension de una matriz
A.shape

(3, 3)

In [ ]:
# ver cantidad de elementos de una matriz
A.size

9

In [ ]:
# Ejemplo multiplicación de matrices
A = np.arange(1, 13).reshape(3, 4) #matriz de dimension 3x4
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
B = np.arange(8).reshape(4,2) #matriz de dimension 4x2
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
# Multiplicando A x B
A @ B #resulta en una matriz de dimension 3x2

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

In [ ]:
# Multiplicando B x A
#B @ A

**La matriz identidad, la matriz inversa, la matriz transpuesta y el determinante**

In [ ]:
# Creando una matriz identidad de 2x2
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Multiplicar una matriz por la identidad nos da la misma matriz
A = np.array([[4, 7],
              [2, 6]])
A

array([[4, 7],
       [2, 6]])

In [ ]:
A @ I # AxI = A

array([[4., 7.],
       [2., 6.]])

In [ ]:
# Calculando el determinante de la matriz A
np.linalg.det(A)

10.000000000000002

In [ ]:
# Calculando la inversa de A.
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [ ]:
# A x A_inv nos da como resultado I.
A @ A_inv

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

In [ ]:
# Trasponiendo una matriz
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.transpose(A)

array([[0, 2, 4],
       [1, 3, 5]])